### ISSUE TITLE
Edge network config

### ISSUE THREAD

**Issue by NiranEC77** [kais66/nsx-t-gen#4]
In the parameter file there are two edge networks requested:
edge_data_network_id: "network-33"
edge_management_network_id: "dvportgroup-42"

I assume this refers to the "uplink" network and the "Overlay" network.
There should be 3 networks for the edge:
Management - management 
Uplink - switch communication, can be the same as management but many times is separate 
OverLay - where the tunnel is created

**Comment by kais66** [comment]
Updated the param list for networks:
edge_uplink_network_id: "network-33"
edge_overlay_network_id: "network-33"
edge_management_network_id: "network-33"

Now when invoking the module to install edge node:
            data_network_ids:
            - "{{hostvars[item].edge_uplink_network_id}}"
            - "{{hostvars[item].edge_overlay_network_id}}"
            - "{{hostvars[item].edge_management_network_id}}"
            management_network_id: "{{hostvars[item].edge_management_network_id}}"

I suppose management_network_id should be the same for controller and edges. Planning to make it a single var when exposing names instead of moRefIDs.

**Comment by NiranEC77** [comment]
Controllers and edge not necessarily reside on the s a enetwork or cluster so the moref would be potentially different

**Comment by kais66** [comment]
addressed
